# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7253f4917d3fc0040d324c317050f9a40a74866ede47b531906af281db51482ddd277caacaec996323d7443f43b435d6a34031f83c3e985c14008c6fdc57a978

test:
  secret_key_base: 6e5284e8ddcd2ea4f7033c9f47c34cdea8420ebffdf4ae5cfc59a4c35770f82a28028034345d98cea9326b162cd1ced317a9cfcb54992cee4cc2bad095ae40c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
